FROM python:3.11-slim

WORKDIR /app

# 安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制代码
COPY . .

# 创建媒体目录
RUN mkdir -p media models

# 启动
CMD ["python", "start.py"]